### ISSUE TITLE
Triangle example runs on citra but gets black screen on hardware

### ISSUE THREAD

**Issue by hYdos** [rust3ds/citro3d-rs#12]
Not much to describe. triangle.rs from the `examples` folder runs and displays a triangle on citra but when testing on my n3ds(xl) its a black screen. I'm assuming its waiting/hanging on something as the home menu button is unresponsive. Rosalina is still usable while its like this.

**Comment by ian-h-chamberlain** [comment]
Hmm, I haven't experienced anything like this except when using the GDB stub (in Rosalina menu) to debug homebrew apps with 3dslink. If enabled it usually just displays a black screen until attached. Glad you found a workaround though!
