### ISSUE TITLE
Can't compile citro3d-sys due to error with bindings

### ISSUE THREAD

**Issue by CenTdemeern1** [rust3ds/citro3d-rs#46]
I wanted to compile the triangle example, but it didn't seem to work out very well.
Logs:
https://gist.github.com/CenTdemeern1/fca46a415a0ba8953ee68210c469d77e
Let me know if you need any more information.

**Comment by Meziu** [comment]
Most likely the cause were the changes in https://github.com/rust3ds/ctru-rs/pull/180.

It'll need a bit of work to get fixed.

**Comment by CenTdemeern1** [comment]
> Most likely the cause were the changes in https://github.com/rust3ds/ctru-rs/pull/180.
> 
> It'll need little work to get fixed.

Is there anything I can do to help?
