### ISSUE TITLE
Binding Conflict: Both ctru-sys and citro3d-sys have bindings for the same header

### ISSUE THREAD

**Issue by hYdos** [rust3ds/citro3d-rs#8]
Both ctru-sys and citro3d-sys have bindings for the same header. This causes issues when using both libraries in a project as they are not interchangeable. Not an urgent issue as it has workarounds but could be tidied up.

**Comment by ian-h-chamberlain** [comment]
This is an interesting point, I think the hope was that using the `--allowlist-*` flags for bindgen would help but clearly there might still be some overlap with `ctru-sys`.

From looking through old bindgen issues, it seems like we might be able to use `--blocklist-file` / `--allowlist-file` to prevent bindings to the upstream files. It might also need a `pub use ctru_sys::*;` or something like that just to make everything work properly,	but it's definitely work exploring if it would help prevent this kind of problem.
